# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'crecreProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for crecreProject
  
  pod 'Alamofire', '~> 4.3'
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'Hue'
  pod 'InfiniteLayout'
end
